openapi: 3.0.0
info:
  title: Connector API
  version: 1.0.0
servers:
  - url: https://kianda-test.kianda.com
  - url: http://localhost:4171
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Authorization
  - name: Connector API
paths:
  /Token:
    post:
      tags:
        - Authorization
      summary: Token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                grant_type:
                  type: string
                  example: password
                username:
                  type: string
                  example: demo-user@kianda.com
                password:
                  type: string
                  example: Demo-Password2022
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                access_token: >-
                  xrDoEDmmagKHljulPyPMd5TLw33V1rNCfyHdEaz_sFFiSQjS8ZFfRn_zJoNLGHhaZrmTIXJCxsb-fDu76XSWW8c6qdhq-t-sBhC4ECFJ-WkhJq4kJ5f_U8_y6jgWrFwD6l0icTIELNVKG1VPgS2zU9q4Y5DV09Suxr-0URhCWvpM4iKt9RkyrqeFRzSqENl90kS0T5zQThiYSWJCmQdAtaM70Dcn9nGsfxl5O4gUUCUeM4BzPVVQG5YjSoSU1Ra-3XgEmOKQ54IKCkUHqx6FhnQcBxx9e9fFhTRx6-4EQCjxe-mlrmvLyX1mWjyimtoNq4jznw2H1y6hul_9s6rwJ1W5BvuB0xrRFbJlFRdNuP8xMdb9NOpo4azD-Nt6MKPN4rpX0oIVZV5WZfyDq_V0-jRdCW9FSQs-q9zkpk-t6DZIiQm9RLjI8lzFYNcRZ0WeG-44JT5R_KUd5pWdkRgNRnHentOY0os5JYWmNGBgfdALdg4l66nEFcZJbspXVDfHf-ezHRj9XQMLnKz6XZZ5-45mUhAnsV1URMZz6aVRWh47CqPN0eSBP2dWlWM8N-JZHAeciOn2koLLY4UPfYNGGg
                token_type: bearer
                expires_in: 299
                userName: basic@kianda.com
                userId: 797392a1-bc76-45a3-8cde-ee8976ec0df1
                subscriptionId: 322f14a6-63a0-4c68-b53e-4ca041c0e9ae
                securityStamp: fc471464-1df8-4f58-a9d7-d414d6f1d5c6
                .issued: Wed, 28 Sep 2022 14:37:57 GMT
                .expires: Wed, 28 Sep 2022 14:42:57 GMT
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                error: unsupported_grant_type
  /api/datasources/{id}/query:
    post:
      tags:
        - Connector API
      summary: Send a datasource query
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: null
                action: select
                info:
                  text: Get Countries
                  name: Get Countries
                  type: STRUCTURE
                  filter: ''
                orderBy: null
                orderAscending: false
                paging: null
                rowLimit: 50
                fields:
                  - Country
                  - Country
                conditions: []
                mappings: {}
                filter: ''
                filterBy: Country
                filterMode: startswith
                signature: null
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
              example:
                success: true
                items:
                  - Country: England
                  - Country: Ireland
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
              example:
                Message: An error has occurred.
  /api/datasources/{id}/tree:
    post:
      tags:
        - Connector API
      summary: Metadata
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                success: true
                message: Metadata Action Completed
                items:
                  - name: Get Countries
                    text: Get Countries
                    title: Get Countries
                    icon: fa fa-globe
                    type: STRUCTURE
                    nodes:
                      - name: Country
                        text: Country
                        title: Country
                        icon: ''
                        type: text
                    fields:
                      - name: Country
                        text: Country
                        title: Country
                        icon: ''
                        type: text
                    selectable: true
                  - name: Get Cities
                    text: Get Cities
                    title: Get Cities
                    icon: fa fa-globe
                    type: STRUCTURE
                    nodes:
                      - name: Country
                        text: Country
                        title: Country
                        icon: ''
                        type: text
                      - name: City
                        text: City
                        title: City
                        icon: ''
                        type: text
                    fields:
                      - name: Country
                        text: Country
                        title: Country
                        icon: ''
                        type: text
                      - name: City
                        text: City
                        title: City
                        icon: ''
                        type: text
                    selectable: true
        '401':
          description: Unauthorized
          
          content:
            application/json:
              schema:
                type: object
              example:
                Message: Authorization has been denied for this request.
  /api/datasources/{id}/test:
    post:
      tags:
        - Connector API
      summary: Test
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                success: true
                message: Test completed successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
              example:
                Message: Authorization has been denied for this request.
